### ISSUE TITLE
Confirming Setup

### ISSUE THREAD

**Issue by xinhui** [jkotchoff/adwords_conversion_tracking_titanium_module#1]
Hi,

I'm using your module and it's seems working well, but according to admob documentation i should see a "Google: Ping successful." logged to the console.

I'm only getting a "GoogleConversionPing: Sending ping with IDFA" ... without confirmation.

https://developers.google.com/app-conversion-tracking/

Thanks

**Comment by awadeyar** [comment]
AdwordsConversionTrackingTitaniumModule is not working after adding the new 64 bit architecture settings. Is anyone used this module to track the conversion tracking. After adding the new settings in the Xcode project and built and created the module using .build.py. If I run the following command to check the which all architecture it supports it shows it support all architecture Command :"xcrun lipo -info libcom.geoplus.adwordsconversiontracking.a" Result: "Architectures in the fat file: libcom.geoplus.adwordsconversiontracking.a are: armv7 i386 x86_64 arm64 "

When I use the module in my project it will give the following error.

"[ERROR] : ** BUILD FAILED ** [ERROR] : The following build commands failed: [ERROR] : Ld build/MyProject.build/Debug-iphonesimulator/MyProject.build/Objects-normal/x86_64/MyProject normal x86_64 [ERROR] : (1 failure)"

I am using the Titanium SDK 3.5.0. Xcode 6.1

**Comment by jkotchoff** [comment]
Hey awadeyar, I'm no longer using this module for titanium so cannot confirm that it is working. I instead choose to perform a custom conversion tracking technique by constructing a device 'fingerprint' using: 
https://github.com/bestiejs/platform.js/

ie. the following javascript snippet is run on a web-page on our site and also in a hidden webview in the titanium app. The web-page logs the visits, the HTTP_REFERER and the ?source= http parameter into the database for lead tracking. If a new app download occurs within a few days that matches the fingerprint, the download (and subsequent user actions) are attributed to that lead.
```
    <script>
      /*
      Our aim here is to detect variables that will be common across browsers on
      the same device for a reasonably short period. This will allow us to do
      the detection on a website and then again in a hidden webview in an app
      and will hopefully result in the same fingerprint. We will combine this
      with the IP address of the device.
      */

      fingerprint =
        // Detected variables from Javascript.
        (window.navigator.userLanguage || window.navigator.language).toLowerCase() + "|" +
        window.screen.width + "|" +
        window.screen.height + "|" +
        window.screen.colorDepth + "|" +
        new Date().getTimezoneOffset() + "|" +
        // Detected variables from parsing the user agent string
        (platform.manufacturer || "unknown") + "|" +
        (platform.product || "unknown") + "|" +
        platform.os.family + "|" +
        platform.os.version;

      if (typeof Ti !== 'undefined') {
        Ti.App.fireEvent('device_fingerprint', { fingerprint: fingerprint });
      }
      else {
        document.write(fingerprint);
      }
    </script>
```

**Comment by awadeyar** [comment]
Hey jkotchoff ,
I need to know that how did you create the adWordsTracking module(How does it work?).
You are telling about the JavaScript code for titanium web view but my application won't uses the web view.
Please tell me or give me link how the source of the download tracked if we use the java script code.

Thanks,
awadeyar

**Comment by jkotchoff** [comment]
Sorry awadeyar, I never got this module going properly myself. You may want to try contacting xinhui who submitted a pull request on this project:
https://github.com/jkotchoff/adwords_conversion_tracking_titanium_module/pull/2

**Comment by awadeyar** [comment]
Thanks jkotchoff !!

I will contact him.
