### ISSUE TITLE
Not supporting 64 bit  

### ISSUE THREAD

**Issue by awadeyar** [jkotchoff/adwords_conversion_tracking_titanium_module#3]
AdwordsConversionTrackingTitaniumModule is not working after adding the new 64 bit architecture settings. Is anyone used this module to track the conversion tracking. After adding the new settings in the Xcode project and built and created the module using .build.py. 
If I run the following command to check the which all architecture it supports it shows it support all architecture

 Command :"xcrun lipo -info libcom.geoplus.adwordsconversiontracking.a"

Result: "Architectures in the fat file: libcom.geoplus.adwordsconversiontracking.a are: armv7 i386 x86_64 arm64 "

When I use the module in my project it will give the following error.

"[ERROR] : ** BUILD FAILED ** [ERROR] : The following build commands failed: [ERROR] : Ld build/MyProject.build/Debug-iphonesimulator/MyProject.build/Objects-normal/x86_64/MyProject normal x86_64 [ERROR] : (1 failure)"

I am using the Titanium SDK 3.5.0. Xcode 6.1

**Comment by jyounus** [comment]
I had the same issue. I went ahead and created my own version. You can download it from here (64bit ready): https://github.com/jyounus/TiAdwords

**Comment by jkotchoff** [comment]
Fantastic work jyounus.
