### ISSUE TITLE
Module not working with SDK 4.0.0.GA

### ISSUE THREAD

**Issue by gcarignano** [jkotchoff/adwords_conversion_tracking_titanium_module#4]
I've tried compiling the module with the latest titanium SDK, the module compiles correctly but when compiling the app the module just doesnt work. Seems to be missing 64 bits support.

error:
Script Error Couldn't find module: com.geoplus.adwordsconversiontracking for architecture: arm64

Any ideas on how to solve this problem?

Thanks

**Comment by jkotchoff** [comment]
I'd suggest checking out:
https://github.com/jyounus/TiAdwords

as per:
https://github.com/jkotchoff/adwords_conversion_tracking_titanium_module/issues/3

I'll see if I can de-commission this project and point to there for future reference.
